# Makefile
# (C) 2011 Akafugu
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.

MCU ?= attiny4313
F_CPU ?= 8000000L

TARGET = main

SRCS = main.c \
        lcd.c \
        usiTwiSlave.c \
        max5160.c \
        mcp4013.c

# Default values
MAX5160 ?= NO
MCP4013 ?= YES
FEATURE_CHANGE_TWI_ADDRESS ?= YES
FEATURE_SHOW_ADDRESS_ON_STARTUP ?= YES

# These will automatically be checked and set 
VALUE_DEFS += DEFAULT_BRIGHTNESS \
		DEFAULT_CONTRAST

# These will automatically be checked if they are set to YES
YESNO_DEFS += DEMO \
        MAX5160 \
        MCP4013 \
        FEATURE_CHANGE_TWI_ADDRESS \
        FEATURE_SHOW_ADDRESS_ON_STARTUP \
	FEATURE_SAFEMODE
